## File: docker-compose.override-ISLE-Drupal-Build_Tools.yml
##   from https://github.com/DigitalGrinnell/95_override_ISLE_Drupal_Build_Tools
## Created 2019-Apr-01
## M. McFate - Grinnell College Libraries

## To learn more about YAML syntax see
##   https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
##   or https://github.com/Animosity/CraftIRC/wiki/Complete-idiot%27s-introduction-to-yaml.

## The following `version` and `services` keys must exist here, and the 'version' key:value pair must match the corresponding pair used in your `docker-compose.yml` file.
version: '3'
services:
  apache:
    volumes:
      - ./ISLE-Drupal-Build-Tools:/utility-scripts/isle_drupal_build_tools
      
